### ISSUE TITLE
[Lower Quality] as a variance in name

### ISSUE THREAD

**Issue by rezad1393** [colligere/collapse_duplicates#3]
"clip name [group] [Lower Quality]" can you add this so that torrents that just differ in that get grouped together?
also this too?
{Se7enSeas}

or even better can you implement a user input so he can put these variable that get added , himself?

**Comment by colligere** [comment]
Can you give me a couple of examples that have that lower quality tag? I can only find one using search. Release groups currently aren't included because they usually release all qualities. If you have examples of other cases, I can have a look.

Having users add additional tags would require quite a few changes to the script. With the site looking into grouping posts in another way, I don't see myself putting in the time to make those changes.

**Comment by rezad1393** [comment]
can the second suggestion (tag as a user input in script setting) be implemented instead?
I think that would be more work but it would make it more flexible and then user can input the tags he needs instead of asking for one every time.

also thank you goo this script.

**Comment by colligere** [comment]
As I said: I don't have the time to make such a change at the moment.

I didn't originally write the script, I just try to maintain it as best I can since the original author abandoned it. I have nowhere near the coding skills they had, so any larger modification takes me forever to implement.

Feel free to add that feature yourself though. If it doesn't break anything else a pull request is always welcome.

**Comment by rezad1393** [comment]
thanks for the answer.
I didnt see that you are not the original author.
I will close this.
